### ISSUE TITLE
UserInfo panic'ing

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1658]
Seems to happen after a dev rebuild in Tilt; not sure on exact repro steps:

```
2022/03/09 23:36:25 http: panic serving 127.0.0.1:33762: runtime error: invalid memory address or nil pointer dereference
goroutine 455 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0x13a
panic({0x2ab3860, 0x4f83160})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
github.com/coreos/go-oidc/v3/oidc.(*Provider).UserInfo(0x0, {0x3eb4b20, 0xc000af3840}, {0x3e7ccc0, 0xc000cb3680})
	/home/jordan/go/pkg/mod/github.com/coreos/go-oidc/v3@v3.1.0/oidc/oidc.go:247 +0x6e
github.com/weaveworks/weave-gitops/pkg/server/auth.(*AuthServer).UserInfo.func1({0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/home/jordan/Projects/weave-gitops/pkg/server/auth/server.go:326 +0x3a5
net/http.HandlerFunc.ServeHTTP(0xc000d88760, {0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/usr/local/go/src/net/http/server.go:2047 +0x43
net/http.(*ServeMux).ServeHTTP(0xc000722b40, {0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/usr/local/go/src/net/http/server.go:2425 +0x135
net/http.serverHandler.ServeHTTP({0xc00026c7e0}, {0x3eaae20, 0xc000f580e0}, 0xc00055ce00)
	/usr/local/go/src/net/http/server.go:2879 +0x47a
net/http.(*conn).serve(0xc000f22820, {0x3eb4b20, 0xc000af37c0})
	/usr/local/go/src/net/http/server.go:1930 +0x18b8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0xa38
2022/03/09 23:36:26 http: panic serving 127.0.0.1:33780: runtime error: invalid memory address or nil pointer dereference
goroutine 457 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0x13a
panic({0x2ab3860, 0x4f83160})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
github.com/coreos/go-oidc/v3/oidc.(*Provider).UserInfo(0x0, {0x3eb4b20, 0xc000af3900}, {0x3e7ccc0, 0xc000cb37a0})
	/home/jordan/go/pkg/mod/github.com/coreos/go-oidc/v3@v3.1.0/oidc/oidc.go:247 +0x6e
github.com/weaveworks/weave-gitops/pkg/server/auth.(*AuthServer).UserInfo.func1({0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/home/jordan/Projects/weave-gitops/pkg/server/auth/server.go:326 +0x3a5
net/http.HandlerFunc.ServeHTTP(0xc000d88760, {0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/usr/local/go/src/net/http/server.go:2047 +0x43
net/http.(*ServeMux).ServeHTTP(0xc000722b40, {0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/usr/local/go/src/net/http/server.go:2425 +0x135
net/http.serverHandler.ServeHTTP({0xc00026c7e0}, {0x3eaae20, 0xc000f581c0}, 0xc00055d100)
	/usr/local/go/src/net/http/server.go:2879 +0x47a
net/http.(*conn).serve(0xc000f228c0, {0x3eb4b20, 0xc000af3880})
	/usr/local/go/src/net/http/server.go:1930 +0x18b8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0xa38
```

**Comment by Callisto13** [comment]
yeh i was going to look into this today, started after i wired in the superuser. i suspect something authy vanishes on a reload and we are missing a nil check somewhere

**Comment by Callisto13** [comment]
Provider is nil https://github.com/weaveworks/weave-gitops/blob/v2/pkg/server/auth/server.go#L326

**Comment by Callisto13** [comment]
Ah, the FE calls UserInfo to check whether logged in. It does this by checking if the info object returns an email.

When logged in as the superuser, this email is set to "wego-admin". All good. The provider package (even though we are not using OIDC) processes the token fine and the email is found in on the info.

When we reload with Tilt, the provider gets wiped from the authserver, so it can't get the UserInfo. Since most of us refresh or whatever after a reload, the UI call to check whether the user is logged in fails because of this.

So why does this happen? Why is the provider removed or nilled on a hot reload? The AuthServer must be initialised properly, otherwise the subsequent login we all do would fail.
