### ISSUE TITLE
[UI] Error when viewing specific Kustomization

### ISSUE THREAD

**Issue by alexandermarston** [weaveworks/weave-gitops#2981]
**Describe the bug**

When trying to view a Kustomization in the GitOps UI, I receive the following error:

```
Cannot read properties of undefined (reading 'containers')

TypeError: Cannot read properties of undefined (reading 'containers')
    at e.get (https://gitops.curve.app/index.bfe09594.js:17:48622)
    at sortValue (https://gitops.curve.app/index.bfe09594.js:17:265866)
    at https://gitops.curve.app/index.bfe09594.js:8:75302
    at Mt (https://gitops.curve.app/index.bfe09594.js:8:58210)
    at https://gitops.curve.app/index.bfe09594.js:8:75277
    at https://gitops.curve.app/index.bfe09594.js:8:74184
    at https://gitops.curve.app/index.bfe09594.js:8:80664
    at Tr (https://gitops.curve.app/index.bfe09594.js:8:74155)
    at Jr (https://gitops.curve.app/index.bfe09594.js:8:75239)
    at Yn.orderBy (https://gitops.curve.app/index.bfe09594.js:8:105541)
```

Once this error is displayed, if I try to navigate to any of the other screens like Sources or Flux Runtime the error message stays on the screen.

**Environment**

- Weave-Gitops Version: [v0.10.1](https://github.com/weaveworks/weave-gitops/releases/tag/v0.10.1)
- Flux Version: v0.36.0
- Kubernetes version: v1.20.15-eks-fb459a0

**To Reproduce**

1. Login to the Weave GitOps UI
2. Open any Kustomization.

**Expected behavior**

I would expect to see the Kustomization overview page, showing details, events, graph etc. 

**Actual Behavior**

I receive an error message and can not proceed further.

**Additional Context (screenshots, logs, etc)**

The Kustomization is showing as Ready in the Flux CLI.

It seems to error after the second request to GET /v1/child_objects

**Comment by chanwit** [comment]
Thank you @alexandermarston for reporting this.

We'll take a look at it.

**Comment by jpellizzari** [comment]
I have a hunch that this will fix it: https://github.com/weaveworks/weave-gitops/pull/2991

Since we only call `spec.containers` in one place that I can see, it will probably fix it. I would like to reproduce and verify however.
