### ISSUE TITLE
Notification view is broken

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#3082]
**Describe the bug**

Navigating to the notifications view results in an error message:
```
Something went wrong.
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at PR (http://localhost:9001/index.e6fbccac.js:17:327329)
    at Ba (http://localhost:9001/index.e6fbccac.js:1:69959)
    at ru (http://localhost:9001/index.e6fbccac.js:1:122030)
    at Lu (http://localhost:9001/index.e6fbccac.js:1:109303)
    at Ru (http://localhost:9001/index.e6fbccac.js:1:109231)
    at Su (http://localhost:9001/index.e6fbccac.js:1:109094)
    at xu (http://localhost:9001/index.e6fbccac.js:1:106080)
    at http://localhost:9001/index.e6fbccac.js:1:55878
    at v (http://localhost:9001/index.e6fbccac.js:1:133082)
    at to (http://localhost:9001/index.e6fbccac.js:1:55655)
```

<img width="1363" alt="Screenshot 2022-11-29 at 14 43 18" src="https://user-images.githubusercontent.com/19860021/204559761-c44e67e3-cb61-4cc1-b151-0a700ded7277.png">

**Environment**

- Weave-Gitops Version 0.11.0
- Flux Version 0.36.0
- Kubernetes version

**To Reproduce**

- flux install
- install alert/provider - i.e. https://fluxcd.io/flux/guides/notifications/
- navigate to notifications view

**Expected behavior**

Page should show notification controller related objects

**Actual Behavior**

b0rk

**Additional Context (screenshots, logs, etc)**

**Comment by sympatheticmoose** [comment]
I don't believe this is fixed - just added an alert and provider to the staging cluster. 

https://user-images.githubusercontent.com/19860021/205122219-21e269cc-15fe-48bb-ac45-226ca7d84389.mov
