### ISSUE TITLE
Flaky test in gitops-run-logs

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#3192]
```
► round 2 - test action
INFO CREATE OBJECT: gitops-run-logs session-id/20221222-122305.01417.txt
✗ round 2 - test failure
INFO LIST BUCKET
INFO bucketName: gitops-run-logs prefix: prefix:"session-id" page: {Marker:session-id/20221222-122305.01227.txt HasMarker:true MaxKeys:1000}
INFO GET OBJECT Bucket: gitops-run-logs Object: session-id/20221222-122305.01389.txt
INFO GET OBJECT Bucket: gitops-run-logs Object: session-id/20221222-122305.01417.txt
panic: send on closed channel

goroutine 3641 [running]:
github.com/weaveworks/weave-gitops/core/server_test.TestSync.func1.1()
	/home/runner/work/weave-gitops/weave-gitops/core/server/sync_test.go:125 +0x9a
created by github.com/weaveworks/weave-gitops/core/server_test.TestSync.func1
	/home/runner/work/weave-gitops/weave-gitops/core/server/sync_test.go:119 +0x315

Ginkgo ran 33 suites in 3m51.02112323s

There were failures detected in the following suites:
  server ./core/server
```

**Comment by chanwit** [comment]
@makkes this one was from running the test suite.

**Comment by makkes** [comment]
> @makkes this one was from running the test suite.

which test suite? How?

**Comment by opudrovs** [comment]
Ran the test suite in question with a test PR for 100 times first time and 500 times second time — no failures both times:

```
Test Suite Passed
Pass: 500
Fail: 0
```

**Comment by katya-makarevich** [comment]
cannot reproduce
