### ISSUE TITLE
UI tests output errors and warnings

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#3581]
Our UI tests output error messages and warnings. When I run `yarn test` on `main`, I get output like this:

```
 PASS  src/components/Pipelines/__tests__/ListPipelines.test.tsx
  ● Console

    console.error
      { code: 401, message: 'Auth error' }

      at Object.onError (node_modules/react-query/lib/core/query.js:367:36)
      at reject (node_modules/react-query/lib/core/retryer.js:81:48)
      at node_modules/react-query/lib/core/retryer.js:146:9

 PASS  src/components/GitAuth/__tests__/GitlabAuth.test.tsx
  ● Console

    console.warn
      Material-UI: You have provided an out-of-range value `{"value":"https://gitlab.git.dev.weave.works/test"}` for the select component.
      Consider providing a value that matches one of the available options or ''.
      The available values are "".

      at create (node_modules/@material-ui/core/Select/SelectInput.js:366:17)
      at apply (node_modules/react-dom/cjs/react-dom.development.js:23487:20)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)

    console.warn
      Material-UI: You have provided an out-of-range value `{"value":"https://gitlab.git.dev.weave.works/test"}` for the select component.
      Consider providing a value that matches one of the available options or ''.
      The available values are "".

      at create (node_modules/@material-ui/core/Select/SelectInput.js:366:17)
      at apply (node_modules/react-dom/cjs/react-dom.development.js:23487:20)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)

...
```

Note that all tests are passing here. When tests are passing, we should see no output.

**Comment by LappleApple** [comment]
Probably about tweaking verbosity.

**Comment by AlinaGoaga** [comment]
Hey @jpellizzari, jest has got the --silent flag which seems to be doing what we need (it will only show failures). 

Without silent: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDJRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d7c92f66e5c398bb777fdd2128ddcf82804db48c/Screenshot%202023-09-12%20at%2016.48.32.png)

With silent - passing and failing:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaCtRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b71aa8a84cee1d28bacd0039b7d0735a0f8728b4/Screenshot%202023-09-12%20at%2016.49.19.png)

Should be only a matter of adjusting test to run `jest --silent`. Maybe have another option without it, in case we want to see the warnings / document this in the dev doc if someone does?

**Comment by jpellizzari** [comment]
@AlinaGoaga I was imagining we try to fix the warnings instead of suppressing them. Any idea what the level of work would be to fix the root cause?

I would bet that the browser will show those errors as well.

**Comment by AlinaGoaga** [comment]
Ah sorry misunderstood. Will have a look
