### ISSUE TITLE
ReferenceError on the Graph tab

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#3672]
<img width="1524" alt="Screenshot 2023-05-04 at 19 23 00" src="https://user-images.githubusercontent.com/8824708/236296867-f14808d8-deb2-42d8-a511-abbbc3d41224.png">

The graph tab in OSS is broken, tested it in staging and locally.

https://gitops.euw1.wego-gke.weave.works/kustomization/graph?clusterName=Default&name=flux-system&namespace=flux-system

```
Full trace (with sourceMap on):
act-dom.production.min.js:216 ReferenceError: $22b18e23564de7e8$exports is not defined
    at yQ (ReconciliationGraph.tsx:102:16)
    at bo (react-dom.production.min.js:157:137)
    at ol (react-dom.production.min.js:267:460)
    at jl (react-dom.production.min.js:250:347)
    at zl (react-dom.production.min.js:250:278)
    at Ql (react-dom.production.min.js:250:138)
    at kl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at v (scheduler.production.min.js:18:343)
    at ri (react-dom.production.min.js:122:325)
F
```

**Comment by opudrovs** [comment]
Results of research:

- It looks like the error is related to the following PR, in which some parcel packages were upgraded:
https://github.com/weaveworks/weave-gitops/pull/3651/files

I had a similar error in this PR:
https://github.com/weaveworks/weave-gitops/pull/3640

and fixed it by adding an `alias` to package.json to help parcel resolve imports (please see the PR description for more details).

Something similar might work here, but I cannot think of a quick fix right now.

- It is possible the error occurs because of d3 not initialized properly. If I add a debug message `console.log(d3)` right before the place where d3 is used first time, the graph is displayed (so, maybe a delay is needed to initialize it)

**Comment by jpellizzari** [comment]
Probably something `undefined` here: https://github.com/weaveworks/weave-gitops-enterprise/tree/main/ui-cra/src/components/GitOpsSets

The error makes me think there is a module not being loaded

**Comment by jpellizzari** [comment]
> And the error points to the line on which d3 is first used in the graph:

I don't see this in the stack trace. What is the indication of this?

**Comment by opudrovs** [comment]
The trace with the line number is in the PR description:
```
Full trace (with sourceMap on):
act-dom.production.min.js:216 ReferenceError: $22b18e23564de7e8$exports is not defined
    **at yQ (ReconciliationGraph.tsx:102:16)**
    at bo (react-dom.production.min.js:157:137)
    at ol (react-dom.production.min.js:267:460)
    at jl (react-dom.production.min.js:250:347)
    at zl (react-dom.production.min.js:250:278)
    at Ql (react-dom.production.min.js:250:138)
    at kl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at v (scheduler.production.min.js:18:343)
    at ri (react-dom.production.min.js:122:325)
F
```

**Comment by opudrovs** [comment]
at yQ (ReconciliationGraph.tsx:102:16)

**Comment by opudrovs** [comment]
At least this is what I see in the trace when turning sourceMap on.
