### ISSUE TITLE
UI Build fails on npm start

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#699]
On node v14.15.1 (npm v7.21.1) I get the following output

```
➜  ui git:(main) ✗ npm install                                                                                                [ 21.08.31 | 18:18 ]

> @weaveworks/weave-gitops@0.2.4 preinstall
> npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions


up to date, audited 1546 packages in 2s

171 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Bianca/.npm/_logs/2021-08-31T16_18_50_324Z-debug.log
Install for [ 'npm-force-resolutions@latest' ] failed with code 1
npm ERR! code 1
npm ERR! path /Users/Bianca/Documents/WeaveWorks/weave-gitops
npm ERR! command failed
npm ERR! command sh -c npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Bianca/.npm/_logs/2021-08-31T16_18_50_414Z-debug.log
➜  ui git:(main) ✗ npm start                                                                                                  [ 21.08.31 | 18:18 ]

> @weaveworks/weave-gitops@0.2.4 start
> parcel serve --port 4567 ui/index.html

Server running at http://localhost:4567
🚨 Build failed.

@parcel/transformer-typescript-tsc: directoryExists is not a function

  TypeError: directoryExists is not a function
  at Object.matchFiles (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/typescript/lib/typescript.js:20102:17)
  at ParseConfigHost.readDirectory (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/@parcel/ts-utils/lib/FSHost.js:105:20)
  at getFileNamesFromConfigSpecs (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/typescript/lib/typescript.js:40747:40)
  at getFileNames (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/typescript/lib/typescript.js:40250:29)
  at parseJsonConfigFileContentWorker (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/typescript/lib/typescript.js:40183:24)
  at Object.parseJsonConfigFileContent (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/typescript/lib/typescript.js:40124:16)
  at loadTSConfig (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/@parcel/ts-utils/lib/loadTSConfig.js:51:44)
  at async loadPluginConfig (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/@parcel/core/lib/requests/ConfigRequest.js:65:21)
  at async Transformation.loadTransformerConfig
  (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/@parcel/core/lib/Transformation.js:520:5)
  at async Transformation.loadPipeline (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/@parcel/core/lib/Transformation.js:459:20)
```

Downgraded to npm 6.14.13 and got
```
➜  ui git:(main) ✗ npm install                             [ 21.08.31 | 18:45 ]

> @weaveworks/weave-gitops@0.2.4 preinstall /Users/Bianca/Documents/WeaveWorks/weave-gitops
> npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions

npm WARN @weaveworks/weave-gitops@0.2.4 No license field.

added 6 packages, removed 6 packages, updated 12 packages and audited 1564 packages in 7.14s

170 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npx: installed 6 in 1.079s
npm WARN @weaveworks/weave-gitops@0.2.4 No license field.

audited 1548 packages in 24.921s

169 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

➜  ui git:(main) ✗ npm  start                              [ 21.08.31 | 18:45 ]

> @weaveworks/weave-gitops@0.2.4 start /Users/Bianca/Documents/WeaveWorks/weave-gitops
> parcel serve --port 4567 ui/index.html

Error: No native build was found for platform=darwin arch=x64 runtime=node abi=88 uv=1 libc=glibc node=15.3.0
    loaded from: /Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/lmdb-store

    at Function.load.path (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/node-gyp-build/index.js:59:9)
    at load (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/node-gyp-build/index.js:21:30)
    at Object.<anonymous> (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/lmdb-store/index.js:7:49)
    at Module._compile (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _lmdbStore (/Users/Bianca/Documents/WeaveWorks/weave-gitops/node_modules/@parcel/cache/lib/LMDBCache.js:31:39)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @weaveworks/weave-gitops@0.2.4 start: `parcel serve --port 4567 ui/index.html`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @weaveworks/weave-gitops@0.2.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Bianca/.npm/_logs/2021-08-31T16_46_52_151Z-debug.log
```

**Comment by jpellizzari** [comment]
Could not reproduce on linux.
```
$ node -v
v15.3.0
$ npm -v
7.0.14
```

I suspect this is related to a bad node version or some Xcode build tools issue based on this line:
```
No native build was found for platform=darwin arch=x64 runtime=node abi=88 uv=1 libc=glibc node=15.3.0
```

**Comment by foot** [comment]
https://github.com/parcel-bundler/parcel/issues/6779

Its a new typescript I think.

```patch
diff --git a/package.json b/package.json
index 51f38a1..d275f0d 100644
--- a/package.json
+++ b/package.json
@@ -108,6 +108,6 @@
     "parcel": "^2.0.0-beta.3.1",
     "react-test-renderer": "^17.0.2",
     "ts-jest": "^26.5.6",
-    "typescript": "^4.2.4"
+    "typescript": "~4.2.4"
   }
 }
```

Fixes it.

**Comment by foot** [comment]
Another workaround is (probably):

```
rm -rf node_modules
npm ci
```

cc @bia
